#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 24 23:28:30 2017

@author: abdulbarinoori
"""
import requests
from bs4 import BeautifulSoup


url = 'http://www.dailymail.co.uk/home/index.html'
r = requests.get(url)

soup = BeautifulSoup(r.content, "html.parser")
links = soup.find_all("h2",{"class":"linkro-darkred"})
#a = soup.find_all("a",)

for link in links:
   
    print(link).get_text().encode('utf-8')


